# Competencia Local

| Gimnasio | Seguidores IG | Precios (mensual / anual / promos) | Inscripción | Dirección / Sedes | Horarios | Servicios principales | Fortalezas | Debilidades | Diferenciación Partner Gym |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| **Partner Gym** | 10,6k | 2 meses $63 / Trimestral $90 / Semestral $160 / Anual $300 | No cobra insc. | Cuenca (sede actual + Rácar nov. + Remigio ene.) | L–D (amplios, todo el día) | Musculación, cardio, baile, yoga, funcional, retos, bar suplementos, eventos comunidad | Comunidad activa, planes flexibles, rápido crecimiento digital, cercanía | Comunicación de promos poco clara en el pasado, aún en proceso de consolidar branding | **Posicionarse como el gym más transparente, social y cercano (Nunca entrenes solo)** |
| **Dorian** | 17k | $38 mensual + $10 insc. / $162 semestral  | $10 | 4 sedes en Cuenca (Parque Industrial, Cebollar, Gonzales Suárez, El Tiempo) | L–V 5am–11pm / S–D 8am–6pm | Pesas, aeróbicos, funcional, spinning, crossfit, box, suplementos, snack, sauna | Gran trayectoria, variedad de servicios, múltiples sedes | Imagen tradicional, precios percibidos altos, saturación en horarios peak | Partner puede diferenciarse en claridad de planes y experiencia social |
| **Target Gym** | 9,1k | $34,90 mensual + $25 insc. / $22,90 mensual anual | - | Av. Ordóñez Lasso, Cuenca | L–D horario extendido | Spinning, bailoterapia, yoga, box, funcional, cafetería, musculación | Precio accesible en anual, variedad de clases sociales | Instalaciones percibidas menos premium, poca estrategia digital | Partner puede posicionarse como premium accesible y con eventos únicos |
| **Sparta Gym** | 9,2k | $31 mensual efectivo / $205 anual | $6–6,50 | 5 sedes en Cuenca (Ricaurte, Milchichig, Totoracocha, Av. Amérocas, Yana Urco) | L–V 5am–11pm / S–D 8am–6pm | Pesas, cardio, funcional, spinning, crossfit, fitboxing, bailoterapia, cancha sintética | Amplia cobertura geográfica, gran variedad de actividades | Marca menos aspiracional, instalaciones heterogéneas entre sedes | Partner puede adueñarse del branding moderno y aspiracional |
| **Cam Gym** | 5,2k | $35 mensual / Promo 4m $100 (gratis insc.) | Gratis promo | Nicolás Sojos y Gonzalo Cordero, Cuenca | L–V 5am–10pm / S 7am–1pm / D 8am–12pm | Musculación, spinning, cardio box | Comunidad fiel, precios accesibles, promos frecuentes | Menor infraestructura, menos variedad de servicios | Partner puede diferenciarse con amplitud de servicios y experiencia premium |
| **Smart Fit** | 118k (Ecuador) | $29,90 + IVA mensual / $19,90 primer mes | $9,90 | Wayra Plaza | Horarios extendidos, varias 24/7 | Multisede, app, invitados gratis, sillas masaje, clases grupales, Smart Fit GO | Precios bajos, tecnología avanzada, acceso multisede | Experiencia impersonal, poco sentido de comunidad local | Partner puede destacarse como opción local, cercana y personalizada |
| **Golden Fit** | 2,3k | $35 mensual $276 anual / promo 3x2 | $10 | Av. de las Américas y Camino Viejo, Cuenca | L–V 5am–11pm / S–D 8am–6pm | Bailoterapia, spinning, funcional, fitboxing, musculación | Imagen aspiracional, promociones atractivas (3x2) | Público reducido, precios similares a grandes sin extra diferenciador | Partner puede diferenciarse con branding moderno + comunidad activa |
| **Fitness Room** | 4,1k | $35 mensual / $280 anual | $0 | Paseo de los Cañaris y Puertas del Sol | N/D | Musculación, bailoterapia, funcional, entrenadores personalizados | Equipos nuevos, buena atención personalizada | Marca poco reconocida, limitada en infraestructura | Partner puede explotar su mayor visibilidad digital y expansión de sedes |
| **Farru Fitness** | 2,3k | $35 mensual + $10 insc. / $5 día / $20 (15 días) | $10 | Bolívar & Tarqui, Cuenca | L–V 5am–10pm / S 8am–6pm | Bailoterapia, spinning, funcional, ambiente motivador | Fuerza en clases sociales, coaches cercanos | Limitado en pesas y maquinaria | Partner puede diferenciarse con equilibrio entre social + equipos premium |
- **Fortaleza a explotar:** comunidad social, planes flexibles y buena presencia digital (10,6k seguidores).
- **Oportunidad clara:** diferenciarse como el gym más transparente y social de Cuenca, frente a competidores que confunden con precios, inscripción y letras pequeñas.
- **Territorio digital:** salvo Dorian y Smart Fit, Partner ya supera en seguidores a varios → debe reforzar contenido aspiracional y de comunidad.
- **Posicionamiento aspiracional-local:** no competir en precio con Smart Fit, sino en experiencia y cercanía.